version: '3'
services:
 postgres:
  build:
   context: .
   dockerfile: Dockerfile_postgres
  container_name: redmine_postgres
  ports:
    - '5432:5432'
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  networks:
   redmine-static:
    ipv4_address: 172.25.0.12

 redmine:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: redmine_app
   env_file: app.env
   networks:
    redmine-static:
     ipv4_address: 172.25.0.13
   links:
    - postgres

 nginx:
   build:
    context: .
    dockerfile: Dockerfile_nginx
   links:
    - redmine
   ports:
    - '8080:80'

   networks:
    redmine-static:
     ipv4_address: 172.25.0.14



networks:
  redmine-static:
    ipam:
     config:
      - subnet: 172.25.0.0/16
