FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils

COPY ./app /redmine

RUN rm -rf /etc/nginx/sites-available/default
RUN rm -rf /etc/nginx/sites-enabled/default
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d/redmine.conf


CMD [ "nginx", "-g", "daemon off;" ]
